### PR TITLE
Release Web Packager HTTP Server.

### PR DESCRIPTION
**Pull request by yuizumi**
This is a joint work of @tomokinat, @banaag, and @yuizumi.

### CODE REVIEW

**Comment by yuizumi** [comment]
Hmm, go-acme/lego seems to use crypto/ed25519 thus require Go 1.13+. Should we require Go 1.13+ (or maybe Go 1.14+), or should we keep support for Go 1.11/1.12 (e.g. by using older version of go-acme/lego)? hashicorp/go-multierror v1.1.0+ also requires Go 1.14.

**Comment by banaag** [comment]
My choice would be to require go 1.14+ since hashicorp/go-multierror also requires it. I don't think we gain anything by supporting older versions of go.

**Comment by banaag** [comment]
Note that golang policy supports last 2 major versions: https://golang.org/doc/devel/release.html#policy

**Comment by yuizumi** [comment]
This PR is ready to go now. PTAL.

**Pull request merged**
